baseUri: '/micro-CMS'
templates: 'templates'
tmpDir: 'tmp'

project:
  title: "uCMS Demo"
  heading:
    en: "Demo uCMS Project"
    cs: "uCMS Demíčko"
  author: "Martin Kruliš"
  description: "Demonstration how to use uCMS framework."
  keywords: "demo,framework,uCMS"

directories:
  pages:
    - PassThrough
    - Menu
    - Html
    - Markdown
  resources:
    - PassThrough
  downloads:
    - Download

langs:
  - en
  - cs
